// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBjv5viMtPCYWSkrL3MILFBeoJ2O96DI',
    appId: '1:1020023204307:web:fae8750a8f827e8d42a726',
    messagingSenderId: '1020023204307',
    projectId: 'komunoto-apps',
    authDomain: 'komunoto-apps.firebaseapp.com',
    storageBucket: 'komunoto-apps.appspot.com',
    measurementId: 'G-9G2P7YMF4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZLy5lJJY6Exc9KuwTT434eEjNQI4e3g',
    appId: '1:1020023204307:android:4fe1c65b4debff9e42a726',
    messagingSenderId: '1020023204307',
    projectId: 'komunoto-apps',
    storageBucket: 'komunoto-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKGSwgrZNK4Ylo7T10qWZ5PwWEwA9XG8I',
    appId: '1:1020023204307:ios:42a2f4ec33d4806842a726',
    messagingSenderId: '1020023204307',
    projectId: 'komunoto-apps',
    storageBucket: 'komunoto-apps.appspot.com',
    iosBundleId: 'com.example.komunoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKGSwgrZNK4Ylo7T10qWZ5PwWEwA9XG8I',
    appId: '1:1020023204307:ios:d6d5b50b98f6743e42a726',
    messagingSenderId: '1020023204307',
    projectId: 'komunoto-apps',
    storageBucket: 'komunoto-apps.appspot.com',
    iosBundleId: 'com.example.komunoto.RunnerTests',
  );
}
